[package]
name = "SynchroSite"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
serde = { version = "1.0.209", features = ["derive"] }  
tera = "1.20.0"
mime = "0.3.17"